version: '2'

services:
  log-aggregator:
    container_name: log-aggregator
    image: petprojects/log-aggregator:${BUILD_VERSION}
    network_mode: bridge
    environment:
      - CONSUL_ENVIRONMENT
      - CONSUL_ADDRESS
    build:
      context: ./src/Presentation.ConsoleApplication
      dockerfile: Dockerfile
      args:
        source: ${OUTPUT_PATH}
